Vagrant.configure("2") do |config|

  # 1. Web Tier (Nginx) - Ubuntu
  config.vm.define "web01" do |web01|
    web01.vm.box = "hashicorp/bionic64" # Ubuntu 18.04 or use "ubuntu/jammy64" for 22.04
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "800"
      vb.name = "web01_nginx"
    end
  end

  # 2. Application Tier (Tomcat) - CentOS
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # PDF asks for 4200MB, but I set 2GB to be safe for your laptop. Increase if you have 16GB+ RAM.
      vb.cpus = 2
      vb.name = "app01_tomcat"
    end
  end

  # 3. Message Queue (RabbitMQ) - CentOS
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.13"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
      vb.name = "rmq01_rabbitmq"
    end
  end

  # 4. Cache Tier (Memcached) - CentOS
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "900"
      vb.name = "mc01_memcached"
    end
  end

  # 5. Database Tier (MariaDB) - CentOS
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "db01_mariadb"
    end
  end

end